version: "3.7"

services:
  database:
    image: postgres:15
    restart: always
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weblabeling
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - husion  # Connect the database service to the "husion" network

  backend:
    image: champkub6/weblabeling-backend
    restart: always
    ports:
      - 8000:${SERVER_PORT}
    depends_on:
      - database
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - husion  # Connect the backend service to the "husion" network

  frontend:
    image: bbbbz/weblabeling-frontend:2023
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_SERVER_URL: http://3.212.197.74:8000
    networks:
      - husion  # Connect the frontend service to the "husion" network

volumes:
  database-storage:

networks:
  husion:
    name: husion
    external: false

