FROM node:20

WORKDIR /app

COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json

RUN yarn

COPY ./prisma ./prisma
COPY ./src ./src

RUN yarn prisma generate

RUN yarn build

EXPOSE 8000

CMD yarn start:prod